# k8s/cart/cart-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cart-secret
  namespace: shop
type: Opaque
stringData:
  ConnectionStrings__Redis: "cart-redis:6379"
  ConnectionStrings__CatalogService: "http://catalog:5001"