apiVersion: v1
kind: Secret
metadata:
  name: catalog-secret
  namespace: shop
type: Opaque
stringData:
  ConnectionStrings__CatalogDb: "Host=catalog-db;Port=5432;Database=catalog;Username=postgres;Password=postgres"
